// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dynibyqrcbxneiwjyahn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5bmlieXFyY2J4bmVpd2p5YWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjM3NjIsImV4cCI6MjA2ODMzOTc2Mn0.Dr-GmXwz-IOMUAWrJHfoRvekkZcBNtlnJIQKC4wjCcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});